#!/usr/bin/env bash
#
# run_pizzly_on_existing_kallisto_annotated.sh
#
# Heavily annotated wrapper to run pizzly on existing kallisto --fusion outputs.
#
# Purpose (short)
#  - You already ran kallisto with the --fusion workflow. Each sample folder under
#    KALLISTO_OUT contains a fusion.txt generated by kallisto.
#  - This script runs pizzly on each fusion.txt and writes per-sample pizzly outputs
#    into a PIZZLY_OUT directory (one subdir per sample).
#
# Important behavior notes
#  - This script DOES NOT run kallisto; it expects fusion.txt files to already exist.
#  - It will skip any sample for which a pizzly JSON output already exists (safe re-run).
#  - It logs stdout+stderr to a run log in your EXISTING_RUN directory.
#
# Safety / reproducibility notes (read these)
#  - The script expects pizzly to be available on PATH (activated via conda or module).
#  - It expects the same reference transcriptome FASTA and (recommended) matching GTF that
#    were used when building the kallisto index/run. Mismatched references will produce
#    confusing results.
#  - The pizzly cache file name is written into each sample output dir; you can reuse the
#    cache across runs if desired, but be careful when changing reference files.
#
# Quick test suggestion
#  - Before running on the whole cohort, try one sample manually:
#      pizzly -k 31 --gtf /path/ref.gtf --fasta /path/ref.fa.gz --output /tmp/pizz_test <path-to-one-fusion.txt>
#    Confirm outputs and that the JSON/fasta appear correct before batch running.
#
# -----------------------------------------------------------------------------
set -euo pipefail   # strict: exit on any error, undefined var is an error, pipeline fails on any non-zero
# (this is good — keeps you from running on partial state)

###############################
# EDIT THESE PATHS / SETTINGS #
###############################

# Path to your existing kallisto run that produced fusion.txt files. Edit this!
EXISTING_RUN="/home/jgd/Documents/bioinformatics_working/output/run_20251215_135715"

# Path inside the kallisto run where per-sample kallisto outputs live; each sample folder should contain fusion.txt
# Example structure expected:
#   KALLISTO_OUT/sample1/fusion.txt
#   KALLISTO_OUT/sample2/fusion.txt
KALLISTO_OUT="${EXISTING_RUN}/kallisto"

# Where pizzly outputs will be written (one subdir per sample)
PIZZLY_OUT="${EXISTING_RUN}/pizzly"

# Reference transcriptome FASTA (the same transcripts used for kallisto index)
# IMPORTANT: use the same FASTA used to build the kallisto index for your fusion run.
REF_TRANSCRIPTS_FA="/home/jgd/Documents/bioinformatics_working/reference/danio_rerio.grcz11.cdna.all.fa.gz"

# Matching GTF annotation (recommended). pizzly uses GTF for gene/transcript mapping and filtering.
REF_GTF="/home/jgd/Documents/bioinformatics_working/reference/danio_rerio.grcz11.110.gtf.gz"

# Fragment insert size (mean fragment length) for pizzly - tune to your library
# This affects how pizzly aligns split/paired reads and estimates support.
PIZZLY_INSERT_SIZE=300

# K-mer length passed to pizzly (-k): must match the k used by kallisto index (commonly 31).
KMER_LENGTH=31

########################
# NO EDITS BELOW HERE  #
########################

# Run identifier & log file (timestamped to avoid overwriting)
RUN_ID="$(date +%Y%m%d_%H%M%S)"
LOG_FILE="${EXISTING_RUN}/pizzly_run_${RUN_ID}.log"

# Create output directory if missing
mkdir -p "${PIZZLY_OUT}"

# Redirect all stdout/stderr to both console and the log file (tee)
exec > >(tee -a "${LOG_FILE}") 2>&1

# Print header with run info
echo "======================================="
echo " PIZZLY on existing kallisto fusion outputs"
echo " Run ID: ${RUN_ID}"
echo " Date:   $(date)"
echo "======================================="
echo
echo "EXISTING_RUN:        ${EXISTING_RUN}"
echo "KALLISTO_OUT:        ${KALLISTO_OUT}"
echo "PIZZLY_OUT:          ${PIZZLY_OUT}"
echo "REF_TRANSCRIPTS_FA:  ${REF_TRANSCRIPTS_FA}"
echo "REF_GTF:             ${REF_GTF}"
echo

#########################
# Sanity checks
#########################

# Helper to check that a binary is discoverable on PATH. If not found, bail with helpful message.
check_bin() {
    local b="$1"
    if ! command -v "${b}" >/dev/null 2>&1; then
        echo "ERROR: '${b}' not found in PATH. Load module or conda env first." >&2
        exit 1
    fi
}

# Ensure pizzly is available
check_bin "pizzly"

# Check that the kallisto output directory exists
if [[ ! -d "${KALLISTO_OUT}" ]]; then
    echo "ERROR: KALLISTO_OUT does not exist: ${KALLISTO_OUT}" >&2
    exit 1
fi

# Check reference FASTA exists
if [[ ! -f "${REF_TRANSCRIPTS_FA}" ]]; then
    echo "ERROR: Transcript FASTA not found: ${REF_TRANSCRIPTS_FA}" >&2
    exit 1
fi

# Check GTF exists
if [[ ! -f "${REF_GTF}" ]]; then
    echo "ERROR: GTF not found: ${REF_GTF}" >&2
    exit 1
fi

#########################
# Discover fusion.txt files
#########################

echo
echo "---------------------------------------"
echo " Discovering fusion.txt files..."
echo "---------------------------------------"

# nullglob: if pattern matches nothing, expands to nothing (no literal pattern)
shopt -s nullglob

# Look for fusion.txt in each immediate subdirectory of KALLISTO_OUT
# This yields an array of filenames, e.g. /.../kallisto/sample1/fusion.txt
FUSION_FILES=( "${KALLISTO_OUT}"/*/fusion.txt )

# If none found, abort: user likely pointed to wrong directory or kallisto hasn't been run
if [[ ${#FUSION_FILES[@]} -eq 0 ]]; then
    echo "ERROR: No fusion.txt files found under ${KALLISTO_OUT}" >&2
    exit 1
fi

echo "Found ${#FUSION_FILES[@]} fusion.txt files:"
printf '  %s\n' "${FUSION_FILES[@]}"

#########################
# Run pizzly on each fusion.txt
#########################

echo
echo "---------------------------------------"
echo " Running pizzly..."
echo "---------------------------------------"

# Loop over each fusion.txt discovered above
for FUSION_TXT in "${FUSION_FILES[@]}"; do
    # SAMPLE_DIR is the kallisto sample directory containing fusion.txt
    SAMPLE_DIR="$(dirname "${FUSION_TXT}")"
    SAMPLE="$(basename "${SAMPLE_DIR}")"   # sample name derived from directory name

    # Make a per-sample pizzly output directory
    P_OUT="${PIZZLY_OUT}/${SAMPLE}"
    mkdir -p "${P_OUT}"

    # Define the pizzly output prefix; pizzly will write several files with this prefix:
    #   <prefix>.json (primary machine-readable results)
    #   <prefix>.fusions.fasta (supporting sequences)
    # and possibly other intermediate files.
    PIZZLY_PREFIX="${P_OUT}/pizzly"
    PIZZLY_JSON="${PIZZLY_PREFIX}.json"

    echo
    echo "[PIZZLY] Sample: ${SAMPLE}"
    echo "  fusion.txt:   ${FUSION_TXT}"
    echo "  Output dir:   ${P_OUT}"
    echo "  Output prefix:${PIZZLY_PREFIX}"

    # Safety: if pizzly JSON already exists, assume this sample was processed and skip.
    # This makes the script re-runnable (idempotent for already-processed samples).
    if [[ -f "${PIZZLY_JSON}" ]]; then
        echo "  Detected existing pizzly output (${PIZZLY_JSON}), skipping this sample."
        continue
    fi

    # ------------------------
    # pizzly command explanation:
    #  -k KMER: the k-mer length used when kallisto index was built; must match kallisto
    #  --gtf: GTF file for transcript/gene mapping and annotation
    #  --cache: path for pizzly to write a small cache file (improves speed if reused)
    #  --align-score: pizzly alignment scoring parameter (default varies by version)
    #  --insert-size: mean fragment length of your library (paired-end)
    #  --fasta: reference transcriptome FASTA (same sequences used by kallisto)
    #  --output: prefix (pizzly writes .json, .fusions.fasta etc with this prefix)
    #  final argument: path to kallisto fusion.txt (input expected)
    #
    # For more options, run 'pizzly --help' — different pizzly versions may support different flags.
    # ------------------------

    pizzly \
        -k "${KMER_LENGTH}" \
        --gtf "${REF_GTF}" \
        --cache "${P_OUT}/pizzly.cache.txt" \
        --align-score 2 \
        --insert-size "${PIZZLY_INSERT_SIZE}" \
        --fasta "${REF_TRANSCRIPTS_FA}" \
        --output "${PIZZLY_PREFIX}" \
        "${FUSION_TXT}"

    # Check exit status implicitly via set -e; if we reach here, pizzly returned 0.
    echo "[PIZZLY] Done: ${SAMPLE}"
    echo "  Expected outputs in: ${P_OUT}"
    echo "    - ${PIZZLY_PREFIX}.json"
    echo "    - ${PIZZLY_PREFIX}.fusions.fasta"
    echo "    - (other supporting files printed by pizzly)"
done

echo
echo "======================================="
echo " Pizzly processing finished."
echo " PIZZLY_OUT: ${PIZZLY_OUT}"
echo " Log file:   ${LOG_FILE}"
echo "======================================="
